
CREATE TABLE CLIENTE(
    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(30),
    APELLIDOS VARCHAR(30),
    DIRECCION VARCHAR(40),
    EMAIL VARCHAR(30),
    TELEFONO VARCHAR(15),
	PRIMARY KEY (DNI)
);

CREATE TABLE MECANICO(
    USUARIO VARCHAR(15) NOT NULL,
    CLAVE VARCHAR(15),
    NOMBRE VARCHAR(30),
    APELLIDOS VARCHAR(30),
    VACACIONES INTEGER,
    FECHA_CONTRATO DATE,
    SUELDO NUMERIC(4,2),
	PRIMARY KEY (USUARIO)
);

CREATE TABLE VEHICULO(
    MATRICULA VARCHAR(10) NOT NULL,
    MARCA VARCHAR(15),
    MODELO VARCHAR(15),
    PUERTAS INTEGER,
    FECHA_MATRICULACION DATE,
    COMBUSTIBLE VARCHAR(10),
    CV INTEGER,
    COLOR VARCHAR(15),
	KILOMETRAJE INTEGER,
	DNI VARCHAR(9),
	CONSTRAINT DNI_FK FOREIGN KEY (DNI) REFERENCES CLIENTE (DNI),
	PRIMARY KEY (MATRICULA)
)

CREATE TABLE PARTE_REP(
	ID INTEGER IDENTITY(1,1) NOT NULL,
	ESTADO VARCHAR(15),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	PRESUPUESTO NUMERIC(5,2),
	COMENTARIO VARCHAR(max),	
	USUARIO VARCHAR(15),
	MATRICULA VARCHAR(10),
	PRIMARY KEY (ID),
	CONSTRAINT USUARIO_FK FOREIGN KEY (USUARIO) REFERENCES MECANICO (USUARIO),
    CONSTRAINT MATRICULA_FK FOREIGN KEY (MATRICULA) REFERENCES VEHICULO (MATRICULA)
)

